package access.mite;

public class BlackBox extends LoadRunner {
             public static void main(String args[])
             {
            	 /*BlackBox box=new BlackBox();
            	 box.test();
            	 box.testcases();
            	 Selenium sel=new Selenium();
            	 sel.testcases();*/
            	 LoadRunner load=new BlackBox();
            	 load.testcases();
            	 load=new Selenium();
            	 load.testcases();
            	 
             }
             @Override
             public void testcases()
             {
            	 System.out.println("Generated by user as well as automatic");
             }
             
}
class Selenium extends LoadRunner
{
	 @Override
	 public void testcases()
	 {
		 System.out.println("Selenium auto");
	 }
}
abstract class LoadRunner{
	public void test()
	{
		System.out.println("load capacity of mite");
		
	}
	abstract public void testcases();
	
}
